### ISSUE TITLE
How to request Access Token after Authentication

### ISSUE THREAD

**Issue by yili1992** [joaojosefilho/vuejsOidcClient#2]
I have finished Authentication, then i want to get Access Token   via https://xxxxx/connect/token

**Comment by joaojosefilho** [comment]
Use this method

In vue-js, I use 'Promise' to call the methods in sync mode
```
getAcessToken(){
    return new Promise((resolve, reject) => {
      mgr.getUser().then(function (user) {
          return resolve(user.access_token)        
      }).catch(function (err) {
        console.log(err)
        return reject(err)
      });
    })
  }
```
In this link, I create examples of methods using the oidc-client library:
https://github.com/joaojosefilho/vuejsOidcClient/blob/master/src/services/SecurityService.js

oicd-client Documentation for more details:
https://github.com/IdentityModel/oidc-client-js/wiki

**Comment by joaojosefilho** [comment]
Did you solve your problem?

**Comment by joaojosefilho** [comment]
I will close this issui. You can open this issui if you have more questions.
