### ISSUE TITLE
UserInfo Endpoint not called

### ISSUE THREAD

**Issue by ConnorJBishop** [joaojosefilho/vuejsOidcClient#3]
Correct me if I am wrong but it would seem that in your set up the UserInfo endpoint is not called. You have `loadUserInfo: true` in your `Oidc.UserManager` options in [SecruityService.js](https://github.com/joaojosefilho/vuejsOidcClient/blob/master/src/services/SecurityService.js) but this has no effect because it is the UserManager instance in [callback.html](https://github.com/joaojosefilho/vuejsOidcClient/blob/master/static/callback.html) which deals with the signIn response. Should the `loadUserInfo: true` go in the `callback.html` UserManager instead?

**Comment by joaojosefilho** [comment]
you're right

`var mgr = new Oidc.UserManager({userStore: new Oidc.WebStorageStateStore(), loadUserInfo: true});`

Thanks

**Comment by joaojosefilho** [comment]
Do you have one more suggestion?

**Comment by ConnorJBishop** [comment]
Not at the moment. It’s a very helpful project, thank you 👍

**Comment by joaojosefilho** [comment]
Thanks for suggestion!
