### ISSUE TITLE
the img directory is unable to locate

### ISSUE THREAD

**Issue by bigbirdhzp** [joaojosefilho/vuejsOidcClient#6]
when i run this project, it appear this situation:
![image](https://user-images.githubusercontent.com/22903159/49003272-9615bf80-f19c-11e8-84e4-32e77ec0ecd5.png)

I find is the source is the "webpack.config.base.js":
![image](https://user-images.githubusercontent.com/22903159/49003368-bd6c8c80-f19c-11e8-844d-2918ce644e9e.png)

I think you may forget to delete the code

**Comment by joaojosefilho** [comment]
I forgot to create the img folder. I already committed the patch. Thanks for reporting the bug!
