### ISSUE TITLE
Funcionamento no internet Explore 11

### ISSUE THREAD

**Issue by patrickmonteiro** [joaojosefilho/vuejsOidcClient#7]
Essa na verdade é uma **dúvida**!

O seu projeto está funcionamento corretamente no IE 11 ?
Usei a sua implementação como base para utilizar dentro do Quasar Framework, porém recentemente tive que testa-lo no IE 11 e Edge, e recebo erros no console como por exemplo : 
![image](https://user-images.githubusercontent.com/13258255/49340313-4e23ec00-f625-11e8-91bf-615e4ef19ee2.png)

Debbuguei um pouco mais no edge e cheguei aqui:
![image](https://user-images.githubusercontent.com/13258255/49340321-5ed46200-f625-11e8-9791-cda71a137655.png)

Porém não consigo afirmar corretamente o que utiliza esta propriedade, ou se parte do OIDC não está passando pelo processo de polyfill do babel.

**Comment by joaojosefilho** [comment]
Bom dia @patrickmonteiro. Não posso fazer o teste agora , mas vou tentar olhar isso ainda hoje.

**Comment by patrickmonteiro** [comment]
Irei fazer o mesmo hoje, criarei um projeto do zero, e testarei somente com a biblioteca. Qualquer avanço, trago aqui.
Obrigado

**Comment by joaojosefilho** [comment]
O Internet explorer 11 não estava reconhecendo a função Promise. Eu adicionei a linha 

`import 'babel-polyfill';`

nos scripts SecurityService.js e ApiService.js. Agora, o meu projeto está funcionando no IE11.

Estou fazendo testes no IE11 no windows 10

![ie11](https://user-images.githubusercontent.com/10532267/49341973-63a01280-f633-11e8-9658-2222f3072282.png)

**Comment by joaojosefilho** [comment]
Meu projeto também está funcionando no Edge

**Comment by patrickmonteiro** [comment]
Cara, vou testar! Acho que isso vai resolver no meu também! Assim que testar te dou um feedback.

**Comment by joaojosefilho** [comment]
Eu instalei o babel-polyfill usando o comando abaixo

npm install --save babel-polyfill

Depois eu só adicionei os imports

**Comment by patrickmonteiro** [comment]
O quasar já tem o Babel polyfill, acredito que não vou precisar instalar! Se funcionar eu vou te pagar um lanche cara !

**Comment by patrickmonteiro** [comment]
@joaojosefilho , nos meus testes em casa o erro do 'from' desapareceu com o babel-polyfill. Amanhã faço o teste na empresa e te dou o feedback!

**Comment by joaojosefilho** [comment]
Beleza

**Comment by patrickmonteiro** [comment]
@joaojosefilho funcionou quase perfeitamente! Em alguns pc's funcionou bem, em outros estranhamente ele joga o modo de compatibilidade do IE para o 7. Então, além de importar o babel-polyfill adicionei o meta no meu index.template.html, que posteriormente a build vira o index.html da aplicação:

` <meta http-equiv="X-UA-Compatible" content="IE=edge,IE=11">`

Este meta força a compatibilidade com o Edge e IE11 logo ao iniciar.
Muito obrigado pela ajuda!

**Comment by joaojosefilho** [comment]
Beleza @patrickmonteiro. Você está me devendo um lanche!

**Comment by patrickmonteiro** [comment]
@joaojosefilho me manda um email para eng.patrickmonteiro@gmail.com
