### ISSUE TITLE
silent renew control

### ISSUE THREAD

**Issue by mteodor** [joaojosefilho/vuejsOidcClient#9]
how can you decrease the renew interval?
currently silent-renew.html is being hit every second and I tried to put automaticSilentRenew=false
but nothing changes, also I've tried to silentRequestTimeout to increase but it seemed no efect.

**Comment by joaojosefilho** [comment]
The access token lifetime is set in the identity provider. I made the identity provider using identityserver4.

in class config.cs(https://github.com/joaojosefilho/IdentityServer4AndApi/blob/master/IdentityServer4.IDP/Config.cs) i define the accessToken lifetime using the accesstokenlifetime attribute.

The oidc-client library renews the token according to the time set in accesstokenlifetime.

In script SecurityService.js(https://github.com/joaojosefilho/vuejsOidcClient/blob/master/src/services/SecurityService.js) there are two attributes that work with renewing accesstoken: automaticSilentRenew and accessTokenExpiringNotificationTime.

accessTokenExpiringNotificationTime: The number of seconds before an access token is to expire to raise the accessTokenExpiring event

**Comment by joaojosefilho** [comment]
Did you solve your problem?

**Comment by joaojosefilho** [comment]
I will close this issui. You can open this issui if you have more questions.
